/* Allegro datafile object indexes, produced by dat v4.4.3, Unix */
/* Datafile: data/phantom1.dat */
/* Date: Sun Sep  4 12:27:54 2022 */
/* Do not hand edit! */

#define PHANTGFX_DAT                     0        /* FILE */

#define PHANTGFX_DAT_BACK000_BMP         0        /* BMP  */
#define PHANTGFX_DAT_BACK001_BMP         1        /* BMP  */
#define PHANTGFX_DAT_BACK002_BMP         2        /* BMP  */
#define PHANTGFX_DAT_BACK003_BMP         3        /* BMP  */
#define PHANTGFX_DAT_BACK004_BMP         4        /* BMP  */
#define PHANTGFX_DAT_BACK005_BMP         5        /* BMP  */
#define PHANTGFX_DAT_BACK006_BMP         6        /* BMP  */
#define PHANTGFX_DAT_BACK007_BMP         7        /* BMP  */
#define PHANTGFX_DAT_BACK008_BMP         8        /* BMP  */
#define PHANTGFX_DAT_BACK009_BMP         9        /* BMP  */
#define PHANTGFX_DAT_DEC00_0_BMP         10       /* BMP  */
#define PHANTGFX_DAT_DEC01_0_BMP         11       /* BMP  */
#define PHANTGFX_DAT_DEC02_0_BMP         12       /* BMP  */
#define PHANTGFX_DAT_DEC03_0_BMP         13       /* BMP  */
#define PHANTGFX_DAT_DEC04_0_BMP         14       /* BMP  */
#define PHANTGFX_DAT_DEC05_0_BMP         15       /* BMP  */
#define PHANTGFX_DAT_DEC06_0_BMP         16       /* BMP  */
#define PHANTGFX_DAT_DEC07_0_BMP         17       /* BMP  */
#define PHANTGFX_DAT_DEC08_0_BMP         18       /* BMP  */
#define PHANTGFX_DAT_DEC09_0_BMP         19       /* BMP  */
#define PHANTGFX_DAT_DEC10_0_BMP         20       /* BMP  */
#define PHANTGFX_DAT_DEC11_0_BMP         21       /* BMP  */
#define PHANTGFX_DAT_DEC12_0_BMP         22       /* BMP  */
#define PHANTGFX_DAT_DEC13_0_BMP         23       /* BMP  */
#define PHANTGFX_DAT_DEC14_0_BMP         24       /* BMP  */
#define PHANTGFX_DAT_DEC15_0_BMP         25       /* BMP  */
#define PHANTGFX_DAT_DEC16_0_BMP         26       /* BMP  */
#define PHANTGFX_DAT_DEC17_0_BMP         27       /* BMP  */
#define PHANTGFX_DAT_DEC18_0_BMP         28       /* BMP  */
#define PHANTGFX_DAT_DEC19_0_BMP         29       /* BMP  */
#define PHANTGFX_DAT_DEC20_0_BMP         30       /* BMP  */
#define PHANTGFX_DAT_DEC21_0_BMP         31       /* BMP  */
#define PHANTGFX_DAT_DEC22_0_BMP         32       /* BMP  */
#define PHANTGFX_DAT_DEC23_0_BMP         33       /* BMP  */
#define PHANTGFX_DAT_DEC24_0_BMP         34       /* BMP  */
#define PHANTGFX_DAT_DEC25_0_BMP         35       /* BMP  */
#define PHANTGFX_DAT_DEC26_0_BMP         36       /* BMP  */
#define PHANTGFX_DAT_DEC27_0_BMP         37       /* BMP  */
#define PHANTGFX_DAT_DEC28_0_BMP         38       /* BMP  */
#define PHANTGFX_DAT_DEC29_0_BMP         39       /* BMP  */
#define PHANTGFX_DAT_DEC30_0_BMP         40       /* BMP  */
#define PHANTGFX_DAT_DEC31_0_BMP         41       /* BMP  */
#define PHANTGFX_DAT_DEC32_0_BMP         42       /* BMP  */
#define PHANTGFX_DAT_DEC33_0_BMP         43       /* BMP  */
#define PHANTGFX_DAT_DEC34_0_BMP         44       /* BMP  */
#define PHANTGFX_DAT_DEC35_0_BMP         45       /* BMP  */
#define PHANTGFX_DAT_DEC36_0_BMP         46       /* BMP  */
#define PHANTGFX_DAT_DEC37_0_BMP         47       /* BMP  */
#define PHANTGFX_DAT_DEC38_0_BMP         48       /* BMP  */
#define PHANTGFX_DAT_DEC39_0_BMP         49       /* BMP  */
#define PHANTGFX_DAT_DEC40_0_BMP         50       /* BMP  */
#define PHANTGFX_DAT_DEC41_0_BMP         51       /* BMP  */
#define PHANTGFX_DAT_DEC42_0_BMP         52       /* BMP  */
#define PHANTGFX_DAT_DEC42_BMP           53       /* BMP  */
#define PHANTGFX_DAT_DEC43_0_BMP         54       /* BMP  */
#define PHANTGFX_DAT_DEC44_0_BMP         55       /* BMP  */
#define PHANTGFX_DAT_DEC45_0_BMP         56       /* BMP  */
#define PHANTGFX_DAT_DEC46_0_BMP         57       /* BMP  */
#define PHANTGFX_DAT_DEC47_0_BMP         58       /* BMP  */
#define PHANTGFX_DAT_DEC48_0_BMP         59       /* BMP  */
#define PHANTGFX_DAT_DEC49_0_BMP         60       /* BMP  */
#define PHANTGFX_DAT_DEC50_0_BMP         61       /* BMP  */
#define PHANTGFX_DAT_DEC51_0_BMP         62       /* BMP  */
#define PHANTGFX_DAT_DEC52_0_BMP         63       /* BMP  */
#define PHANTGFX_DAT_DEC53_0_BMP         64       /* BMP  */
#define PHANTGFX_DAT_DEC54_0_BMP         65       /* BMP  */
#define PHANTGFX_DAT_DEC55_0_BMP         66       /* BMP  */
#define PHANTGFX_DAT_DEC56_0_BMP         67       /* BMP  */
#define PHANTGFX_DAT_DEC57_0_BMP         68       /* BMP  */
#define PHANTGFX_DAT_DEC58_0_BMP         69       /* BMP  */
#define PHANTGFX_DAT_DEC59_0_BMP         70       /* BMP  */
#define PHANTGFX_DAT_DEC60_0_BMP         71       /* BMP  */
#define PHANTGFX_DAT_DEC61_0_BMP         72       /* BMP  */
#define PHANTGFX_DAT_DEC62_0_BMP         73       /* BMP  */
#define PHANTGFX_DAT_DEC63_0_BMP         74       /* BMP  */
#define PHANTGFX_DAT_DEC64_0_BMP         75       /* BMP  */
#define PHANTGFX_DAT_DEC65_0_BMP         76       /* BMP  */
#define PHANTGFX_DAT_DEC66_0_BMP         77       /* BMP  */
#define PHANTGFX_DAT_DEC67_0_BMP         78       /* BMP  */
#define PHANTGFX_DAT_DEC68_0_BMP         79       /* BMP  */
#define PHANTGFX_DAT_DEC69_0_BMP         80       /* BMP  */
#define PHANTGFX_DAT_DEC70_0_BMP         81       /* BMP  */
#define PHANTGFX_DAT_DEC71_0_BMP         82       /* BMP  */
#define PHANTGFX_DAT_DEC72_0_BMP         83       /* BMP  */
#define PHANTGFX_DAT_DEC73_0_BMP         84       /* BMP  */
#define PHANTGFX_DAT_DEC74_0_BMP         85       /* BMP  */
#define PHANTGFX_DAT_DEC75_0_BMP         86       /* BMP  */
#define PHANTGFX_DAT_DEC76_0_BMP         87       /* BMP  */
#define PHANTGFX_DAT_DEC77_0_BMP         88       /* BMP  */
#define PHANTGFX_DAT_DEC78_0_BMP         89       /* BMP  */
#define PHANTGFX_DAT_DEC79_0_BMP         90       /* BMP  */
#define PHANTGFX_DAT_DEC80_0_BMP         91       /* BMP  */
#define PHANTGFX_DAT_DEC81_0_BMP         92       /* BMP  */
#define PHANTGFX_DAT_DEC82_0_BMP         93       /* BMP  */
#define PHANTGFX_DAT_DEC83_0_BMP         94       /* BMP  */
#define PHANTGFX_DAT_DEC84_0_BMP         95       /* BMP  */
#define PHANTGFX_DAT_DEC85_0_BMP         96       /* BMP  */
#define PHANTGFX_DAT_DEC86_0_BMP         97       /* BMP  */
#define PHANTGFX_DAT_DEC87_0_BMP         98       /* BMP  */
#define PHANTGFX_DAT_DEC88_0_BMP         99       /* BMP  */
#define PHANTGFX_DAT_DEC89_0_BMP         100      /* BMP  */
#define PHANTGFX_DAT_DEC90_0_BMP         101      /* BMP  */
#define PHANTGFX_DAT_DEC91_0_BMP         102      /* BMP  */
#define PHANTGFX_DAT_DEC92_0_BMP         103      /* BMP  */
#define PHANTGFX_DAT_DEC93_0_BMP         104      /* BMP  */
#define PHANTGFX_DAT_DEC94_0_BMP         105      /* BMP  */
#define PHANTGFX_DAT_DEC95_0_BMP         106      /* BMP  */
#define PHANTGFX_DAT_DEC96_0_BMP         107      /* BMP  */
#define PHANTGFX_DAT_DEC97_0_BMP         108      /* BMP  */
#define PHANTGFX_DAT_DEC98_0_BMP         109      /* BMP  */
#define PHANTGFX_DAT_DEC99_0_BMP         110      /* BMP  */
#define PHANTGFX_DAT_DECO100_0_BMP       111      /* BMP  */
#define PHANTGFX_DAT_DECO101_0_BMP       112      /* BMP  */
#define PHANTGFX_DAT_DECO102_0_BMP       113      /* BMP  */
#define PHANTGFX_DAT_DECO103_0_BMP       114      /* BMP  */
#define PHANTGFX_DAT_DECO104_0_BMP       115      /* BMP  */
#define PHANTGFX_DAT_DECO105_0_BMP       116      /* BMP  */
#define PHANTGFX_DAT_DECO106_0_BMP       117      /* BMP  */
#define PHANTGFX_DAT_DECO107_0_BMP       118      /* BMP  */
#define PHANTGFX_DAT_DECO108_0_BMP       119      /* BMP  */
#define PHANTGFX_DAT_DECO109_0_BMP       120      /* BMP  */
#define PHANTGFX_DAT_DECO110_0_BMP       121      /* BMP  */
#define PHANTGFX_DAT_DECO110_1_BMP       122      /* BMP  */
#define PHANTGFX_DAT_DECO110_2_BMP       123      /* BMP  */
#define PHANTGFX_DAT_DECO110_3_BMP       124      /* BMP  */
#define PHANTGFX_DAT_DECO110_4_BMP       125      /* BMP  */
#define PHANTGFX_DAT_DECO110_5_BMP       126      /* BMP  */
#define PHANTGFX_DAT_DECO110_6_BMP       127      /* BMP  */
#define PHANTGFX_DAT_DECO110_7_BMP       128      /* BMP  */
#define PHANTGFX_DAT_DECO111_0_BMP       129      /* BMP  */
#define PHANTGFX_DAT_DECO111_1_BMP       130      /* BMP  */
#define PHANTGFX_DAT_DECO111_2_BMP       131      /* BMP  */
#define PHANTGFX_DAT_DECO111_3_BMP       132      /* BMP  */
#define PHANTGFX_DAT_DECO111_4_BMP       133      /* BMP  */
#define PHANTGFX_DAT_DECO111_5_BMP       134      /* BMP  */
#define PHANTGFX_DAT_DECO111_6_BMP       135      /* BMP  */
#define PHANTGFX_DAT_DECO111_7_BMP       136      /* BMP  */
#define PHANTGFX_DAT_DECO112_0_BMP       137      /* BMP  */
#define PHANTGFX_DAT_DECO112_1_BMP       138      /* BMP  */
#define PHANTGFX_DAT_DECO112_2_BMP       139      /* BMP  */
#define PHANTGFX_DAT_DECO112_3_BMP       140      /* BMP  */
#define PHANTGFX_DAT_DECO112_4_BMP       141      /* BMP  */
#define PHANTGFX_DAT_DECO112_5_BMP       142      /* BMP  */
#define PHANTGFX_DAT_DECO112_6_BMP       143      /* BMP  */
#define PHANTGFX_DAT_DECO112_7_BMP       144      /* BMP  */
#define PHANTGFX_DAT_DECO113_0_BMP       145      /* BMP  */
#define PHANTGFX_DAT_DECO113_1_BMP       146      /* BMP  */
#define PHANTGFX_DAT_DECO113_2_BMP       147      /* BMP  */
#define PHANTGFX_DAT_DECO113_3_BMP       148      /* BMP  */
#define PHANTGFX_DAT_DECO113_4_BMP       149      /* BMP  */
#define PHANTGFX_DAT_DECO113_5_BMP       150      /* BMP  */
#define PHANTGFX_DAT_DECO113_6_BMP       151      /* BMP  */
#define PHANTGFX_DAT_DECO113_7_BMP       152      /* BMP  */
#define PHANTGFX_DAT_DECO122_0_BMP       153      /* BMP  */
#define PHANTGFX_DAT_DECO122_1_BMP       154      /* BMP  */
#define PHANTGFX_DAT_DECO122_2_BMP       155      /* BMP  */
#define PHANTGFX_DAT_DECO122_3_BMP       156      /* BMP  */
#define PHANTGFX_DAT_DECO123_0_BMP       157      /* BMP  */
#define PHANTGFX_DAT_DECO124_0_BMP       158      /* BMP  */
#define PHANTGFX_DAT_DECO125_0_BMP       159      /* BMP  */
#define PHANTGFX_DAT_DECO126_0_BMP       160      /* BMP  */
#define PHANTGFX_DAT_DECO127_0_BMP       161      /* BMP  */
#define PHANTGFX_DAT_DECO127_1_BMP       162      /* BMP  */
#define PHANTGFX_DAT_DECO127_2_BMP       163      /* BMP  */
#define PHANTGFX_DAT_DECO127_3_BMP       164      /* BMP  */
#define PHANTGFX_DAT_DECO127_4_BMP       165      /* BMP  */
#define PHANTGFX_DAT_DECO127_5_BMP       166      /* BMP  */
#define PHANTGFX_DAT_DECO127_6_BMP       167      /* BMP  */
#define PHANTGFX_DAT_DECO127_7_BMP       168      /* BMP  */
#define PHANTGFX_DAT_DECO127_8_BMP       169      /* BMP  */
#define PHANTGFX_DAT_DECO128_0_BMP       170      /* BMP  */
#define PHANTGFX_DAT_DECO128_1_BMP       171      /* BMP  */
#define PHANTGFX_DAT_DECO128_2_BMP       172      /* BMP  */
#define PHANTGFX_DAT_DECO128_3_BMP       173      /* BMP  */
#define PHANTGFX_DAT_DECO128_4_BMP       174      /* BMP  */
#define PHANTGFX_DAT_DECO128_5_BMP       175      /* BMP  */
#define PHANTGFX_DAT_DECO128_6_BMP       176      /* BMP  */
#define PHANTGFX_DAT_DECO128_7_BMP       177      /* BMP  */
#define PHANTGFX_DAT_DECO128_8_BMP       178      /* BMP  */
#define PHANTGFX_DAT_DECO129_0_BMP       179      /* BMP  */
#define PHANTGFX_DAT_DECO129_1_BMP       180      /* BMP  */
#define PHANTGFX_DAT_DECO129_2_BMP       181      /* BMP  */
#define PHANTGFX_DAT_DECO129_3_BMP       182      /* BMP  */
#define PHANTGFX_DAT_DECO129_4_BMP       183      /* BMP  */
#define PHANTGFX_DAT_DECO129_5_BMP       184      /* BMP  */
#define PHANTGFX_DAT_DECO129_6_BMP       185      /* BMP  */
#define PHANTGFX_DAT_DECO129_7_BMP       186      /* BMP  */
#define PHANTGFX_DAT_DECO129_8_BMP       187      /* BMP  */
#define PHANTGFX_DAT_DECO129_9_BMP       188      /* BMP  */
#define PHANTGFX_DAT_DECO999_0_BMP       189      /* BMP  */
#define PHANTGFX_DAT_DECO999_1_BMP       190      /* BMP  */
#define PHANTGFX_DAT_DECO999_2_BMP       191      /* BMP  */
#define PHANTGFX_DAT_DECO999_3_BMP       192      /* BMP  */
#define PHANTGFX_DAT_ENE00_0_0_BMP       193      /* BMP  */
#define PHANTGFX_DAT_ENE00_1_0_BMP       194      /* BMP  */
#define PHANTGFX_DAT_ENE00_2_0_BMP       195      /* BMP  */
#define PHANTGFX_DAT_ENE00_3_0_BMP       196      /* BMP  */
#define PHANTGFX_DAT_ENE01_0_0_BMP       197      /* BMP  */
#define PHANTGFX_DAT_ENE01_1_0_BMP       198      /* BMP  */
#define PHANTGFX_DAT_ENE01_2_0_BMP       199      /* BMP  */
#define PHANTGFX_DAT_ENE01_3_0_BMP       200      /* BMP  */
#define PHANTGFX_DAT_ENE02_0_0_BMP       201      /* BMP  */
#define PHANTGFX_DAT_ENE02_1_0_BMP       202      /* BMP  */
#define PHANTGFX_DAT_ENE02_2_0_BMP       203      /* BMP  */
#define PHANTGFX_DAT_ENE02_3_0_BMP       204      /* BMP  */
#define PHANTGFX_DAT_ENE03_0_1_BMP       205      /* BMP  */
#define PHANTGFX_DAT_ENE03_1_1_BMP       206      /* BMP  */
#define PHANTGFX_DAT_ENE03_2_1_BMP       207      /* BMP  */
#define PHANTGFX_DAT_ENE03_3_1_BMP       208      /* BMP  */
#define PHANTGFX_DAT_ENE04_0_0_BMP       209      /* BMP  */
#define PHANTGFX_DAT_ENE04_1_0_BMP       210      /* BMP  */
#define PHANTGFX_DAT_ENE04_2_0_BMP       211      /* BMP  */
#define PHANTGFX_DAT_ENE04_3_0_BMP       212      /* BMP  */
#define PHANTGFX_DAT_ENE05_0_0_BMP       213      /* BMP  */
#define PHANTGFX_DAT_ENE05_1_0_BMP       214      /* BMP  */
#define PHANTGFX_DAT_ENE05_2_0_BMP       215      /* BMP  */
#define PHANTGFX_DAT_ENE05_3_0_BMP       216      /* BMP  */
#define PHANTGFX_DAT_ENE06_0_0_BMP       217      /* BMP  */
#define PHANTGFX_DAT_ENE06_1_0_BMP       218      /* BMP  */
#define PHANTGFX_DAT_ENE06_2_0_BMP       219      /* BMP  */
#define PHANTGFX_DAT_ENE06_3_0_BMP       220      /* BMP  */
#define PHANTGFX_DAT_ENE07_0_0_BMP       221      /* BMP  */
#define PHANTGFX_DAT_ENE07_1_0_BMP       222      /* BMP  */
#define PHANTGFX_DAT_ENE07_2_0_BMP       223      /* BMP  */
#define PHANTGFX_DAT_ENE07_3_0_BMP       224      /* BMP  */
#define PHANTGFX_DAT_ENE08_0_0_BMP       225      /* BMP  */
#define PHANTGFX_DAT_ENE08_1_0_BMP       226      /* BMP  */
#define PHANTGFX_DAT_ENE08_2_0_BMP       227      /* BMP  */
#define PHANTGFX_DAT_ENE08_3_0_BMP       228      /* BMP  */
#define PHANTGFX_DAT_ENE09_0_0_BMP       229      /* BMP  */
#define PHANTGFX_DAT_ENE09_1_0_BMP       230      /* BMP  */
#define PHANTGFX_DAT_ENE09_2_0_BMP       231      /* BMP  */
#define PHANTGFX_DAT_ENE09_3_0_BMP       232      /* BMP  */
#define PHANTGFX_DAT_ENE10_0_0_BMP       233      /* BMP  */
#define PHANTGFX_DAT_ENE10_1_0_BMP       234      /* BMP  */
#define PHANTGFX_DAT_ENE10_2_0_BMP       235      /* BMP  */
#define PHANTGFX_DAT_ENE10_3_0_BMP       236      /* BMP  */
#define PHANTGFX_DAT_ENE11_0_0_BMP       237      /* BMP  */
#define PHANTGFX_DAT_ENE11_1_0_BMP       238      /* BMP  */
#define PHANTGFX_DAT_ENE11_2_0_BMP       239      /* BMP  */
#define PHANTGFX_DAT_ENE11_3_0_BMP       240      /* BMP  */
#define PHANTGFX_DAT_ENE12_0_0_BMP       241      /* BMP  */
#define PHANTGFX_DAT_ENE12_1_0_BMP       242      /* BMP  */
#define PHANTGFX_DAT_ENE12_2_0_BMP       243      /* BMP  */
#define PHANTGFX_DAT_ENE12_3_0_BMP       244      /* BMP  */
#define PHANTGFX_DAT_ENE13_0_0_BMP       245      /* BMP  */
#define PHANTGFX_DAT_ENE13_1_0_BMP       246      /* BMP  */
#define PHANTGFX_DAT_ENE13_2_0_BMP       247      /* BMP  */
#define PHANTGFX_DAT_ENE13_3_0_BMP       248      /* BMP  */
#define PHANTGFX_DAT_ENE14_0_0_BMP       249      /* BMP  */
#define PHANTGFX_DAT_ENE14_1_0_BMP       250      /* BMP  */
#define PHANTGFX_DAT_ENE14_2_0_BMP       251      /* BMP  */
#define PHANTGFX_DAT_ENE14_3_0_BMP       252      /* BMP  */
#define PHANTGFX_DAT_ENE15_0_0_BMP       253      /* BMP  */
#define PHANTGFX_DAT_ENE15_1_0_BMP       254      /* BMP  */
#define PHANTGFX_DAT_ENE15_2_0_BMP       255      /* BMP  */
#define PHANTGFX_DAT_ENE15_3_0_BMP       256      /* BMP  */
#define PHANTGFX_DAT_ENE16_0_1_BMP       257      /* BMP  */
#define PHANTGFX_DAT_ENE16_1_1_BMP       258      /* BMP  */
#define PHANTGFX_DAT_ENE16_2_1_BMP       259      /* BMP  */
#define PHANTGFX_DAT_ENE16_3_1_BMP       260      /* BMP  */
#define PHANTGFX_DAT_ENE17_0_0_BMP       261      /* BMP  */
#define PHANTGFX_DAT_ENE17_1_0_BMP       262      /* BMP  */
#define PHANTGFX_DAT_ENE17_2_0_BMP       263      /* BMP  */
#define PHANTGFX_DAT_ENE17_3_0_BMP       264      /* BMP  */
#define PHANTGFX_DAT_ENE18_0_0_BMP       265      /* BMP  */
#define PHANTGFX_DAT_ENE18_1_0_BMP       266      /* BMP  */
#define PHANTGFX_DAT_ENE18_2_0_BMP       267      /* BMP  */
#define PHANTGFX_DAT_ENE18_3_0_BMP       268      /* BMP  */
#define PHANTGFX_DAT_ENE19_0_1_BMP       269      /* BMP  */
#define PHANTGFX_DAT_ENE19_1_1_BMP       270      /* BMP  */
#define PHANTGFX_DAT_ENE19_2_1_BMP       271      /* BMP  */
#define PHANTGFX_DAT_ENE19_3_1_BMP       272      /* BMP  */
#define PHANTGFX_DAT_ENE20_0_1_BMP       273      /* BMP  */
#define PHANTGFX_DAT_ENE20_1_1_BMP       274      /* BMP  */
#define PHANTGFX_DAT_ENE20_2_1_BMP       275      /* BMP  */
#define PHANTGFX_DAT_ENE20_3_1_BMP       276      /* BMP  */
#define PHANTGFX_DAT_ENE21_0_0_BMP       277      /* BMP  */
#define PHANTGFX_DAT_ENE21_1_0_BMP       278      /* BMP  */
#define PHANTGFX_DAT_ENE21_2_0_BMP       279      /* BMP  */
#define PHANTGFX_DAT_ENE21_3_0_BMP       280      /* BMP  */
#define PHANTGFX_DAT_ENE22_0_0_BMP       281      /* BMP  */
#define PHANTGFX_DAT_ENE22_1_0_BMP       282      /* BMP  */
#define PHANTGFX_DAT_ENE22_2_0_BMP       283      /* BMP  */
#define PHANTGFX_DAT_ENE22_3_0_BMP       284      /* BMP  */
#define PHANTGFX_DAT_ENE23_0_0_BMP       285      /* BMP  */
#define PHANTGFX_DAT_ENE23_1_0_BMP       286      /* BMP  */
#define PHANTGFX_DAT_ENE23_2_0_BMP       287      /* BMP  */
#define PHANTGFX_DAT_ENE23_3_0_BMP       288      /* BMP  */
#define PHANTGFX_DAT_ENE24_0_0_BMP       289      /* BMP  */
#define PHANTGFX_DAT_ENE24_1_0_BMP       290      /* BMP  */
#define PHANTGFX_DAT_ENE24_2_0_BMP       291      /* BMP  */
#define PHANTGFX_DAT_ENE24_3_0_BMP       292      /* BMP  */
#define PHANTGFX_DAT_ENE25_0_0_BMP       293      /* BMP  */
#define PHANTGFX_DAT_ENE25_1_0_BMP       294      /* BMP  */
#define PHANTGFX_DAT_ENE25_2_0_BMP       295      /* BMP  */
#define PHANTGFX_DAT_ENE25_3_0_BMP       296      /* BMP  */
#define PHANTGFX_DAT_ENE26_0_0_BMP       297      /* BMP  */
#define PHANTGFX_DAT_ENE26_1_0_BMP       298      /* BMP  */
#define PHANTGFX_DAT_ENE26_2_0_BMP       299      /* BMP  */
#define PHANTGFX_DAT_ENE26_3_0_BMP       300      /* BMP  */
#define PHANTGFX_DAT_ENE27_0_0_BMP       301      /* BMP  */
#define PHANTGFX_DAT_ENE27_1_0_BMP       302      /* BMP  */
#define PHANTGFX_DAT_ENE27_2_0_BMP       303      /* BMP  */
#define PHANTGFX_DAT_ENE27_3_0_BMP       304      /* BMP  */
#define PHANTGFX_DAT_ENE28_0_0_BMP       305      /* BMP  */
#define PHANTGFX_DAT_ENE28_1_0_BMP       306      /* BMP  */
#define PHANTGFX_DAT_ENE28_2_0_BMP       307      /* BMP  */
#define PHANTGFX_DAT_ENE28_3_0_BMP       308      /* BMP  */
#define PHANTGFX_DAT_ENE29_0_0_BMP       309      /* BMP  */
#define PHANTGFX_DAT_ENE29_1_0_BMP       310      /* BMP  */
#define PHANTGFX_DAT_ENE29_2_0_BMP       311      /* BMP  */
#define PHANTGFX_DAT_ENE29_3_0_BMP       312      /* BMP  */
#define PHANTGFX_DAT_ENE30_0_5_BMP       313      /* BMP  */
#define PHANTGFX_DAT_ENE30_1_5_BMP       314      /* BMP  */
#define PHANTGFX_DAT_ENE30_2_5_BMP       315      /* BMP  */
#define PHANTGFX_DAT_ENE30_3_5_BMP       316      /* BMP  */
#define PHANTGFX_DAT_ENE31_0_0_BMP       317      /* BMP  */
#define PHANTGFX_DAT_ENE31_1_0_BMP       318      /* BMP  */
#define PHANTGFX_DAT_ENE31_2_0_BMP       319      /* BMP  */
#define PHANTGFX_DAT_ENE31_3_0_BMP       320      /* BMP  */
#define PHANTGFX_DAT_ENE32_0_1_BMP       321      /* BMP  */
#define PHANTGFX_DAT_ENE32_1_1_BMP       322      /* BMP  */
#define PHANTGFX_DAT_ENE32_2_1_BMP       323      /* BMP  */
#define PHANTGFX_DAT_ENE32_3_1_BMP       324      /* BMP  */
#define PHANTGFX_DAT_ENE33_0_0_BMP       325      /* BMP  */
#define PHANTGFX_DAT_ENE33_1_0_BMP       326      /* BMP  */
#define PHANTGFX_DAT_ENE33_2_0_BMP       327      /* BMP  */
#define PHANTGFX_DAT_ENE33_3_0_BMP       328      /* BMP  */
#define PHANTGFX_DAT_ENE34_0_0_BMP       329      /* BMP  */
#define PHANTGFX_DAT_ENE34_1_0_BMP       330      /* BMP  */
#define PHANTGFX_DAT_ENE34_2_0_BMP       331      /* BMP  */
#define PHANTGFX_DAT_ENE34_3_0_BMP       332      /* BMP  */
#define PHANTGFX_DAT_ENE35_0_0_BMP       333      /* BMP  */
#define PHANTGFX_DAT_ENE35_1_0_BMP       334      /* BMP  */
#define PHANTGFX_DAT_ENE35_2_0_BMP       335      /* BMP  */
#define PHANTGFX_DAT_ENE35_3_0_BMP       336      /* BMP  */
#define PHANTGFX_DAT_ENE36_0_0_BMP       337      /* BMP  */
#define PHANTGFX_DAT_ENE36_1_0_BMP       338      /* BMP  */
#define PHANTGFX_DAT_ENE36_2_0_BMP       339      /* BMP  */
#define PHANTGFX_DAT_ENE36_3_0_BMP       340      /* BMP  */
#define PHANTGFX_DAT_ENE37_0_0_BMP       341      /* BMP  */
#define PHANTGFX_DAT_ENE37_1_0_BMP       342      /* BMP  */
#define PHANTGFX_DAT_ENE37_2_0_BMP       343      /* BMP  */
#define PHANTGFX_DAT_ENE37_3_0_BMP       344      /* BMP  */
#define PHANTGFX_DAT_ENE38_0_0_BMP       345      /* BMP  */
#define PHANTGFX_DAT_ENE38_1_0_BMP       346      /* BMP  */
#define PHANTGFX_DAT_ENE38_2_0_BMP       347      /* BMP  */
#define PHANTGFX_DAT_ENE38_3_0_BMP       348      /* BMP  */
#define PHANTGFX_DAT_ENE39_0_0_BMP       349      /* BMP  */
#define PHANTGFX_DAT_ENE39_1_0_BMP       350      /* BMP  */
#define PHANTGFX_DAT_ENE39_2_0_BMP       351      /* BMP  */
#define PHANTGFX_DAT_ENE39_3_0_BMP       352      /* BMP  */
#define PHANTGFX_DAT_ENE40_0_0_BMP       353      /* BMP  */
#define PHANTGFX_DAT_ENE40_1_0_BMP       354      /* BMP  */
#define PHANTGFX_DAT_ENE40_2_0_BMP       355      /* BMP  */
#define PHANTGFX_DAT_ENE40_3_0_BMP       356      /* BMP  */
#define PHANTGFX_DAT_ENE41_0_0_BMP       357      /* BMP  */
#define PHANTGFX_DAT_ENE41_1_0_BMP       358      /* BMP  */
#define PHANTGFX_DAT_ENE41_2_0_BMP       359      /* BMP  */
#define PHANTGFX_DAT_ENE41_3_0_BMP       360      /* BMP  */
#define PHANTGFX_DAT_ENE42_0_0_BMP       361      /* BMP  */
#define PHANTGFX_DAT_ENE42_1_0_BMP       362      /* BMP  */
#define PHANTGFX_DAT_ENE42_2_0_BMP       363      /* BMP  */
#define PHANTGFX_DAT_ENE42_3_0_BMP       364      /* BMP  */
#define PHANTGFX_DAT_ENE43_0_0_BMP       365      /* BMP  */
#define PHANTGFX_DAT_ENE43_1_0_BMP       366      /* BMP  */
#define PHANTGFX_DAT_ENE43_2_0_BMP       367      /* BMP  */
#define PHANTGFX_DAT_ENE43_3_0_BMP       368      /* BMP  */
#define PHANTGFX_DAT_ENE44_0_0_BMP       369      /* BMP  */
#define PHANTGFX_DAT_ENE44_1_0_BMP       370      /* BMP  */
#define PHANTGFX_DAT_ENE44_2_0_BMP       371      /* BMP  */
#define PHANTGFX_DAT_ENE44_3_0_BMP       372      /* BMP  */
#define PHANTGFX_DAT_LIFE00_0_BMP        373      /* BMP  */
#define PHANTGFX_DAT_LIFE00_1_BMP        374      /* BMP  */
#define PHANTGFX_DAT_LIFE00_2_BMP        375      /* BMP  */
#define PHANTGFX_DAT_LIFE00_3_BMP        376      /* BMP  */
#define PHANTGFX_DAT_MISC_PHANTOMAS2X_BMP 377      /* BMP  */
#define PHANTGFX_DAT_MISC_PHANTOMASPC_BMP 378      /* BMP  */
#define PHANTGFX_DAT_MISCGAMEOVER_BMP    379      /* BMP  */
#define PHANTGFX_DAT_MISCINIT_BMP        380      /* BMP  */
#define PHANTGFX_DAT_MISCMARC0A_BMP      381      /* BMP  */
#define PHANTGFX_DAT_MISCMARC0B_BMP      382      /* BMP  */
#define PHANTGFX_DAT_MISCMARC0C_BMP      383      /* BMP  */
#define PHANTGFX_DAT_MISCMARC0D_BMP      384      /* BMP  */
#define PHANTGFX_DAT_MISCMARC0E_BMP      385      /* BMP  */
#define PHANTGFX_DAT_MISCMARC0F_BMP      386      /* BMP  */
#define PHANTGFX_DAT_MISCMARC0G_BMP      387      /* BMP  */
#define PHANTGFX_DAT_MISCMARC0H_BMP      388      /* BMP  */
#define PHANTGFX_DAT_MISCMARC1_BMP       389      /* BMP  */
#define PHANTGFX_DAT_MISCMARC2_BMP       390      /* BMP  */
#define PHANTGFX_DAT_MISCMARC3_BMP       391      /* BMP  */
#define PHANTGFX_DAT_MISCTR1_BMP         392      /* BMP  */
#define PHANTGFX_DAT_MISCTR2_BMP         393      /* BMP  */
#define PHANTGFX_DAT_MISCTR2X_BMP        394      /* BMP  */
#define PHANTGFX_DAT_MISCTR3_BMP         395      /* BMP  */
#define PHANTGFX_DAT_MISCTR4_BMP         396      /* BMP  */
#define PHANTGFX_DAT_MISLOGO00_BMP       397      /* BMP  */
#define PHANTGFX_DAT_MISLOGO01_BMP       398      /* BMP  */
#define PHANTGFX_DAT_MISLOGO02_BMP       399      /* BMP  */
#define PHANTGFX_DAT_MISLOGO03_BMP       400      /* BMP  */
#define PHANTGFX_DAT_MISLOGO04_BMP       401      /* BMP  */
#define PHANTGFX_DAT_PHA00_0_0_BMP       402      /* BMP  */
#define PHANTGFX_DAT_PHA00_0_1_BMP       403      /* BMP  */
#define PHANTGFX_DAT_PHA00_1_1_BMP       404      /* BMP  */
#define PHANTGFX_DAT_PHA00_2_1_BMP       405      /* BMP  */
#define PHANTGFX_DAT_PHA00_3_1_BMP       406      /* BMP  */
#define PHANTGFX_DAT_PHA00_4_1_BMP       407      /* BMP  */
#define PHANTGFX_DAT_PHA00_5_1_BMP       408      /* BMP  */
#define PHANTGFX_DAT_PHA00_6_1_BMP       409      /* BMP  */
#define PHANTGFX_DAT_PHA00_7_1_BMP       410      /* BMP  */
#define PHANTGFX_DAT_PHA00_8_1_BMP       411      /* BMP  */
#define PHANTGFX_DAT_PHA01_0_1_BMP       412      /* BMP  */
#define PHANTGFX_DAT_PHA01_1_1_BMP       413      /* BMP  */
#define PHANTGFX_DAT_PHA01_2_1_BMP       414      /* BMP  */
#define PHANTGFX_DAT_PHA01_3_1_BMP       415      /* BMP  */
#define PHANTGFX_DAT_PHA01_4_1_BMP       416      /* BMP  */
#define PHANTGFX_DAT_PHA01_5_1_BMP       417      /* BMP  */
#define PHANTGFX_DAT_PHA01_6_1_BMP       418      /* BMP  */
#define PHANTGFX_DAT_PHA01_7_1_BMP       419      /* BMP  */
#define PHANTGFX_DAT_PHA01_8_1_BMP       420      /* BMP  */
#define PHANTGFX_DAT_PHA02_0_1_BMP       421      /* BMP  */
#define PHANTGFX_DAT_PHA02_1_1_BMP       422      /* BMP  */
#define PHANTGFX_DAT_PHA02_2_1_BMP       423      /* BMP  */
#define PHANTGFX_DAT_PHA02_3_1_BMP       424      /* BMP  */
#define PHANTGFX_DAT_PHA02_4_1_BMP       425      /* BMP  */
#define PHANTGFX_DAT_PHA02_5_1_BMP       426      /* BMP  */
#define PHANTGFX_DAT_PHA02_6_1_BMP       427      /* BMP  */
#define PHANTGFX_DAT_PHA02_7_1_BMP       428      /* BMP  */
#define PHANTGFX_DAT_PHA02_8_1_BMP       429      /* BMP  */
#define PHANTGFX_DAT_PHA03_0_1_BMP       430      /* BMP  */
#define PHANTGFX_DAT_PHA03_1_1_BMP       431      /* BMP  */
#define PHANTGFX_DAT_PHA03_2_1_BMP       432      /* BMP  */
#define PHANTGFX_DAT_PHA03_3_1_BMP       433      /* BMP  */
#define PHANTGFX_DAT_PHA03_4_1_BMP       434      /* BMP  */
#define PHANTGFX_DAT_PHA03_5_1_BMP       435      /* BMP  */
#define PHANTGFX_DAT_PHA03_6_1_BMP       436      /* BMP  */
#define PHANTGFX_DAT_PHA03_7_1_BMP       437      /* BMP  */
#define PHANTGFX_DAT_PHA03_8_1_BMP       438      /* BMP  */
#define PHANTGFX_DAT_PHA04_0_1_BMP       439      /* BMP  */
#define PHANTGFX_DAT_PHA04_1_1_BMP       440      /* BMP  */
#define PHANTGFX_DAT_PHA04_2_1_BMP       441      /* BMP  */
#define PHANTGFX_DAT_PHA04_3_1_BMP       442      /* BMP  */
#define PHANTGFX_DAT_PHA04_4_1_BMP       443      /* BMP  */
#define PHANTGFX_DAT_PHA04_5_1_BMP       444      /* BMP  */
#define PHANTGFX_DAT_PHA04_6_1_BMP       445      /* BMP  */
#define PHANTGFX_DAT_PHA04_7_1_BMP       446      /* BMP  */
#define PHANTGFX_DAT_PHA04_8_1_BMP       447      /* BMP  */
#define PHANTGFX_DAT_PHA05_0_1_BMP       448      /* BMP  */
#define PHANTGFX_DAT_PHA05_1_1_BMP       449      /* BMP  */
#define PHANTGFX_DAT_PHA05_2_1_BMP       450      /* BMP  */
#define PHANTGFX_DAT_PHA05_3_1_BMP       451      /* BMP  */
#define PHANTGFX_DAT_PHA05_4_1_BMP       452      /* BMP  */
#define PHANTGFX_DAT_PHA05_5_1_BMP       453      /* BMP  */
#define PHANTGFX_DAT_PHA05_6_1_BMP       454      /* BMP  */
#define PHANTGFX_DAT_PHA05_7_1_BMP       455      /* BMP  */
#define PHANTGFX_DAT_PHA05_8_1_BMP       456      /* BMP  */
#define PHANTGFX_DAT_PHA06_0_1_BMP       457      /* BMP  */
#define PHANTGFX_DAT_PHA06_1_1_BMP       458      /* BMP  */
#define PHANTGFX_DAT_PHA06_2_1_BMP       459      /* BMP  */
#define PHANTGFX_DAT_PHA06_3_1_BMP       460      /* BMP  */
#define PHANTGFX_DAT_PHA06_4_1_BMP       461      /* BMP  */
#define PHANTGFX_DAT_PHA06_5_1_BMP       462      /* BMP  */
#define PHANTGFX_DAT_PHA06_6_1_BMP       463      /* BMP  */
#define PHANTGFX_DAT_PHA06_7_1_BMP       464      /* BMP  */
#define PHANTGFX_DAT_PHA06_8_1_BMP       465      /* BMP  */
#define PHANTGFX_DAT_PHA07_0_1_BMP       466      /* BMP  */
#define PHANTGFX_DAT_PHA07_1_1_BMP       467      /* BMP  */
#define PHANTGFX_DAT_PHA07_2_1_BMP       468      /* BMP  */
#define PHANTGFX_DAT_PHA07_3_1_BMP       469      /* BMP  */
#define PHANTGFX_DAT_PHA07_4_1_BMP       470      /* BMP  */
#define PHANTGFX_DAT_PHA07_5_1_BMP       471      /* BMP  */
#define PHANTGFX_DAT_PHA07_6_1_BMP       472      /* BMP  */
#define PHANTGFX_DAT_PHA07_7_1_BMP       473      /* BMP  */
#define PHANTGFX_DAT_PHA07_8_1_BMP       474      /* BMP  */
#define PHANTGFX_DAT_PHA08_0_1_BMP       475      /* BMP  */
#define PHANTGFX_DAT_PHA08_1_1_BMP       476      /* BMP  */
#define PHANTGFX_DAT_PHA08_2_1_BMP       477      /* BMP  */
#define PHANTGFX_DAT_PHA08_3_1_BMP       478      /* BMP  */
#define PHANTGFX_DAT_PHA08_4_1_BMP       479      /* BMP  */
#define PHANTGFX_DAT_PHA08_5_1_BMP       480      /* BMP  */
#define PHANTGFX_DAT_PHA08_6_1_BMP       481      /* BMP  */
#define PHANTGFX_DAT_PHA08_7_1_BMP       482      /* BMP  */
#define PHANTGFX_DAT_PHA08_8_1_BMP       483      /* BMP  */
#define PHANTGFX_DAT_PHA09_0_1_BMP       484      /* BMP  */
#define PHANTGFX_DAT_PHA09_1_1_BMP       485      /* BMP  */
#define PHANTGFX_DAT_PHA09_2_1_BMP       486      /* BMP  */
#define PHANTGFX_DAT_PHA09_3_1_BMP       487      /* BMP  */
#define PHANTGFX_DAT_PHA09_4_1_BMP       488      /* BMP  */
#define PHANTGFX_DAT_PHA09_5_1_BMP       489      /* BMP  */
#define PHANTGFX_DAT_PHA09_6_1_BMP       490      /* BMP  */
#define PHANTGFX_DAT_PHA09_7_1_BMP       491      /* BMP  */
#define PHANTGFX_DAT_PHA09_8_1_BMP       492      /* BMP  */
#define PHANTGFX_DAT_PHA10_0_1_BMP       493      /* BMP  */
#define PHANTGFX_DAT_PHA10_1_1_BMP       494      /* BMP  */
#define PHANTGFX_DAT_PHA10_2_1_BMP       495      /* BMP  */
#define PHANTGFX_DAT_PHA10_3_1_BMP       496      /* BMP  */
#define PHANTGFX_DAT_PHA10_4_1_BMP       497      /* BMP  */
#define PHANTGFX_DAT_PHA10_5_1_BMP       498      /* BMP  */
#define PHANTGFX_DAT_PHA10_6_1_BMP       499      /* BMP  */
#define PHANTGFX_DAT_PHA10_7_1_BMP       500      /* BMP  */
#define PHANTGFX_DAT_PHA10_8_1_BMP       501      /* BMP  */
#define PHANTGFX_DAT_PHA11_0_1_BMP       502      /* BMP  */
#define PHANTGFX_DAT_PHA11_1_1_BMP       503      /* BMP  */
#define PHANTGFX_DAT_PHA11_2_1_BMP       504      /* BMP  */
#define PHANTGFX_DAT_PHA11_3_1_BMP       505      /* BMP  */
#define PHANTGFX_DAT_PHA11_4_1_BMP       506      /* BMP  */
#define PHANTGFX_DAT_PHA11_5_1_BMP       507      /* BMP  */
#define PHANTGFX_DAT_PHA11_6_1_BMP       508      /* BMP  */
#define PHANTGFX_DAT_PHA11_7_1_BMP       509      /* BMP  */
#define PHANTGFX_DAT_PHA11_8_1_BMP       510      /* BMP  */
#define PHANTGFX_DAT_PHA12_0_1_BMP       511      /* BMP  */
#define PHANTGFX_DAT_PHA12_1_1_BMP       512      /* BMP  */
#define PHANTGFX_DAT_PHA12_2_1_BMP       513      /* BMP  */
#define PHANTGFX_DAT_PHA12_3_1_BMP       514      /* BMP  */
#define PHANTGFX_DAT_PHA12_4_1_BMP       515      /* BMP  */
#define PHANTGFX_DAT_PHA12_5_1_BMP       516      /* BMP  */
#define PHANTGFX_DAT_PHA12_6_1_BMP       517      /* BMP  */
#define PHANTGFX_DAT_PHA12_7_1_BMP       518      /* BMP  */
#define PHANTGFX_DAT_PHA12_8_1_BMP       519      /* BMP  */
#define PHANTGFX_DAT_PLA00_0_BMP         520      /* BMP  */
#define PHANTGFX_DAT_PLA00_1_BMP         521      /* BMP  */
#define PHANTGFX_DAT_PLA00_2_BMP         522      /* BMP  */
#define PHANTGFX_DAT_PLA00_3_BMP         523      /* BMP  */
#define PHANTGFX_DAT_PLA01_0_BMP         524      /* BMP  */
#define PHANTGFX_DAT_PLA01_1_BMP         525      /* BMP  */
#define PHANTGFX_DAT_PLA01_2_BMP         526      /* BMP  */
#define PHANTGFX_DAT_PLA01_3_BMP         527      /* BMP  */
#define PHANTGFX_DAT_PLA02_0_BMP         528      /* BMP  */
#define PHANTGFX_DAT_PLA02_1_BMP         529      /* BMP  */
#define PHANTGFX_DAT_PLA02_2_BMP         530      /* BMP  */
#define PHANTGFX_DAT_PLA02_3_BMP         531      /* BMP  */
#define PHANTGFX_DAT_PLA03_0_BMP         532      /* BMP  */
#define PHANTGFX_DAT_PLA03_1_BMP         533      /* BMP  */
#define PHANTGFX_DAT_PLA03_2_BMP         534      /* BMP  */
#define PHANTGFX_DAT_PLA03_3_BMP         535      /* BMP  */
#define PHANTGFX_DAT_PLA04_0_BMP         536      /* BMP  */
#define PHANTGFX_DAT_PLA04_1_BMP         537      /* BMP  */
#define PHANTGFX_DAT_PLA04_2_BMP         538      /* BMP  */
#define PHANTGFX_DAT_PLA04_3_BMP         539      /* BMP  */
#define PHANTGFX_DAT_SW00_0_BMP          540      /* BMP  */
#define PHANTGFX_DAT_SW00_1_BMP          541      /* BMP  */
#define PHANTGFX_DAT_SW00_2_BMP          542      /* BMP  */
#define PHANTGFX_DAT_SW00_3_BMP          543      /* BMP  */
#define PHANTGFX_DAT_SW01_0_BMP          544      /* BMP  */
#define PHANTGFX_DAT_SW01_1_BMP          545      /* BMP  */
#define PHANTGFX_DAT_SW01_2_BMP          546      /* BMP  */
#define PHANTGFX_DAT_SW01_3_BMP          547      /* BMP  */
#define PHANTGFX_DAT_X0_BMP              548      /* BMP  */
#define PHANTGFX_DAT_X10_BMP             549      /* BMP  */
#define PHANTGFX_DAT_X1_BMP              550      /* BMP  */
#define PHANTGFX_DAT_X2_BMP              551      /* BMP  */
#define PHANTGFX_DAT_X3_BMP              552      /* BMP  */
#define PHANTGFX_DAT_X4_BMP              553      /* BMP  */
#define PHANTGFX_DAT_X5_BMP              554      /* BMP  */
#define PHANTGFX_DAT_X6_BMP              555      /* BMP  */
#define PHANTGFX_DAT_X7_BMP              556      /* BMP  */
#define PHANTGFX_DAT_X8_BMP              557      /* BMP  */
#define PHANTGFX_DAT_X9_BMP              558      /* BMP  */
#define PHANTGFX_DAT_COUNT               559

#define PHANTSND_DAT                     1        /* FILE */

#define PHANTSND_DAT_BALL_WAV            0        /* SAMP */
#define PHANTSND_DAT_BOING1_WAV          1        /* SAMP */
#define PHANTSND_DAT_BOING2_WAV          2        /* SAMP */
#define PHANTSND_DAT_BUBBLES_WAV         3        /* SAMP */
#define PHANTSND_DAT_CLICK_WAV           4        /* SAMP */
#define PHANTSND_DAT_CLOCK_WAV           5        /* SAMP */
#define PHANTSND_DAT_E10_WAV             6        /* SAMP */
#define PHANTSND_DAT_E12_WAV             7        /* SAMP */
#define PHANTSND_DAT_E13_WAV             8        /* SAMP */
#define PHANTSND_DAT_E16_WAV             9        /* SAMP */
#define PHANTSND_DAT_E19_WAV             10       /* SAMP */
#define PHANTSND_DAT_E1_WAV              11       /* SAMP */
#define PHANTSND_DAT_E20_WAV             12       /* SAMP */
#define PHANTSND_DAT_E22_WAV             13       /* SAMP */
#define PHANTSND_DAT_E24_WAV             14       /* SAMP */
#define PHANTSND_DAT_E2_WAV              15       /* SAMP */
#define PHANTSND_DAT_E30_WAV             16       /* SAMP */
#define PHANTSND_DAT_E32_WAV             17       /* SAMP */
#define PHANTSND_DAT_E35_WAV             18       /* SAMP */
#define PHANTSND_DAT_E41_WAV             19       /* SAMP */
#define PHANTSND_DAT_E4_WAV              20       /* SAMP */
#define PHANTSND_DAT_E5_WAV              21       /* SAMP */
#define PHANTSND_DAT_E6_WAV              22       /* SAMP */
#define PHANTSND_DAT_E7_WAV              23       /* SAMP */
#define PHANTSND_DAT_E8_WAV              24       /* SAMP */
#define PHANTSND_DAT_E9_WAV              25       /* SAMP */
#define PHANTSND_DAT_ENERGY1_WAV         26       /* SAMP */
#define PHANTSND_DAT_EXPLOSION1_WAV      27       /* SAMP */
#define PHANTSND_DAT_GAMEOVER2_WAV       28       /* SAMP */
#define PHANTSND_DAT_HELLACOPTER_WAV     29       /* SAMP */
#define PHANTSND_DAT_HIT_WAV             30       /* SAMP */
#define PHANTSND_DAT_MENUBEGIN_WAV       31       /* SAMP */
#define PHANTSND_DAT_MENUCONT_WAV        32       /* SAMP */
#define PHANTSND_DAT_PUSH_WAV            33       /* SAMP */
#define PHANTSND_DAT_RADAR_WAV           34       /* SAMP */
#define PHANTSND_DAT_ROCKET2_WAV         35       /* SAMP */
#define PHANTSND_DAT_ROCKET_WAV          36       /* SAMP */
#define PHANTSND_DAT_SHOOT_WAV           37       /* SAMP */
#define PHANTSND_DAT_SMOKE1_WAV          38       /* SAMP */
#define PHANTSND_DAT_SMOKE2_WAV          39       /* SAMP */
#define PHANTSND_DAT_SMOKE3_WAV          40       /* SAMP */
#define PHANTSND_DAT_SPACE_WAV           41       /* SAMP */
#define PHANTSND_DAT_SPECCY_WAV          42       /* SAMP */
#define PHANTSND_DAT_TREASURE_WAV        43       /* SAMP */
#define PHANTSND_DAT_TS_WAV              44       /* SAMP */
#define PHANTSND_DAT_WALK_WAV            45       /* SAMP */
#define PHANTSND_DAT_COUNT               46

#define PHANTWLD_DAT                     2        /* WLD  */
#define SONG2_OGG                        3        /* OGGV */
#define SONG3_OGG                        4        /* OGGV */

